[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
web3 = "0.19.0"
tokio = { version = "1", features = ["full"] }
ethers = { version = "2.0.14", features = ["abigen"] }
serde_json = "1.0"